import { useCallback, useEffect, useMemo, useState } from "react";
import { Bell, BellOff, Clock3, Gavel, Gem, Shapes, Shell } from "lucide-react";
import { useParams } from "react-router-dom";
import { api } from "../api";
import { CollectibleVisual } from "../components/CollectibleVisual";
import { MineBackButton } from "../components/MineBackButton";
import { PageTopBar } from "../components/PageTopBar";
import { useApp } from "../context/AppContext";
import { subscribeServerEvent } from "../shared/serverEvents";
import { publishShellBalance } from "../shared/useShellBalance";
import type { CollectibleAuction } from "../shared/collectibles";

export default function CollectibleAuctionDetailPage(){const{id=""}=useParams();const{showToast,user}=useApp();const[a,setA]=useState<CollectibleAuction|null>(null);const[amount,setAmount]=useState("");const[saving,setSaving]=useState(false);const[now,setNow]=useState(Date.now());
 const load=useCallback(async()=>{const d=await api<{auction:CollectibleAuction}>(`/api/collectible-auctions/${id}`,{bypassCache:true,dedupe:false});setA(d.auction);},[id]);
 useEffect(()=>{void load();const poll=window.setInterval(()=>void load(),15_000),clock=window.setInterval(()=>setNow(Date.now()),1000);const u=subscribeServerEvent("collectible_auction_changed",e=>{try{if(JSON.parse(e.data).auctionId===id)void load();}catch{}});const visible=()=>{if(document.visibilityState==="visible")void load();};document.addEventListener("visibilitychange",visible);return()=>{clearInterval(poll);clearInterval(clock);u();document.removeEventListener("visibilitychange",visible);};},[id,load]);
 const minimum=useMemo(()=>a?(a.currentPrice==null?a.startingPrice:a.currentPrice+10):0,[a]);const remain=a?Math.max(0,Math.ceil((new Date(a.endsAt).getTime()-now)/1000)):0;
 async function bid(){const value=Number(amount);if(!Number.isInteger(value)||value<minimum)return showToast(`本次出价不能低于 ${minimum} 贝壳`);setSaving(true);try{const d=await api<{auction:CollectibleAuction;balance:number}>(`/api/collectible-auctions/${id}/bids`,{method:"POST",body:{amount:value,requestId:crypto.randomUUID()}});setA(d.auction);publishShellBalance(user?.id,d.balance);setAmount("");showToast("出价成功");}catch(e){showToast((e as Error).message);}finally{setSaving(false);}}
 async function follow(){if(!a)return;const d=await api<{followed:boolean}>(`/api/collectibles/${a.collectible.id}/follow`,{method:"POST"});setA({...a,collectible:{...a.collectible,followed:d.followed}});showToast(d.followed?"已关注藏品":"已取消关注");}
 if(!a)return <section><PageTopBar title="拍卖详情"/><div className="card h-60 animate-pulse"/></section>;
 return <section className="space-y-3"><PageTopBar title="拍卖详情"/><MineBackButton to="/mine/store/auctions" hideOnDesktop/><div className="grid gap-5 lg:grid-cols-[minmax(0,420px)_1fr]"><CollectibleVisual collectible={a.collectible} className="aspect-[5/6]"/><div className="card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black text-primary">{a.collectible.rarityLabel} · NO.{a.collectible.collectibleNo}</p><h2 className="mt-1 text-2xl font-black text-ink">{a.collectible.name}</h2></div><button className="btn btn-secondary" onClick={()=>void follow()}>{a.collectible.followed?<BellOff size={17}/>:<Bell size={17}/>} {a.collectible.followed?"取消关注":"关注藏品"}</button></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-muted">{a.collectible.description||"暂无描述"}</p><dl className="mt-5 grid grid-cols-2 gap-3" aria-label="藏品档案"><div className="rounded-xl border border-line bg-slate-50 p-4"><dt className="flex items-center gap-2 text-xs font-bold text-muted"><Shapes size={16}/>藏品类型</dt><dd className="mt-2 text-sm font-black text-ink">{a.collectible.collectibleTypeLabel}</dd></div><div className="rounded-xl border border-line bg-slate-50 p-4"><dt className="flex items-center gap-2 text-xs font-bold text-muted"><Gem size={16}/>藏品价值</dt><dd className="mt-2 text-sm font-black text-ink">{a.collectible.collectibleValue.toLocaleString()}</dd></div></dl><p className="mt-2 text-xs leading-5 text-muted">藏品价值仅用于展示与排行榜统计，不代表实际价格。</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-blue-50 p-4"><p className="text-xs text-muted">当前价格</p><p className="mt-1 flex items-center gap-1 text-2xl font-black text-primary"><Shell size={20}/>{a.currentPrice??a.startingPrice}</p></div><div className="rounded-xl bg-amber-50 p-4"><p className="text-xs text-muted">剩余时间</p><p className="mt-1 flex items-center gap-1 text-lg font-black text-amber-700"><Clock3 size={18}/>{a.status==="active"?`${Math.floor(remain/60)}分${String(remain%60).padStart(2,"0")}秒`:a.status==="pending"?"待开拍":"已结束"}</p></div></div>{a.status==="active"&&<div className="mt-5 rounded-2xl border border-line p-4"><p className="text-sm font-black">最低出价 {minimum} 贝壳</p><p className="mt-1 text-xs text-muted">最后一分钟内出现新出价，截止时间自动顺延至该次出价后一分钟。</p><div className="mt-3 flex gap-2"><input className="field" type="number" min={minimum} step="10" value={amount} onChange={e=>setAmount(e.target.value)} placeholder={String(minimum)}/><button className="btn btn-primary shrink-0" disabled={saving||a.isHighestBidder} onClick={()=>void bid()}><Gavel size={17}/>{a.isHighestBidder?"当前最高":"确认出价"}</button></div></div>} {a.status==="sold"&&<p className="mt-5 rounded-xl bg-emerald-50 p-4 font-bold text-emerald-700">成交人：{a.highestBidder?.nickname} · 成交价 {a.currentPrice} 贝壳</p>}</div></div></section>;
}
